"""added email to user

Revision ID: 62102fae2b02
Revises: 0d5008f546bb
Create Date: 2019-08-09 01:05:15.425750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62102fae2b02'
down_revision = '0d5008f546bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
